apiVersion: v1
entries:
  catalogi:
  - apiVersion: v2
    appVersion: 1.52.4
    created: "2025-11-07T13:48:10.835435377Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: "16"
    description: A Helm chart for deploying the Catalogi open source software catalog.
    digest: 12a2ff83f359447cd226d93780ae266d8891ef9a7e58638f9bdfa2ca0d1d402d
    name: catalogi
    type: application
    urls:
    - https://github.com/codegouvfr/catalogi/releases/download/v1.52.4/catalogi-2.0.15.tgz
    version: 2.0.15
  - apiVersion: v2
    appVersion: 1.52.3
    created: "2025-11-07T13:35:17.792714876Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: "16"
    description: A Helm chart for deploying the Catalogi open source software catalog.
    digest: b29f45a895f9b7db791a62534c793dacdf512f0eb3d5966def832e3dd46d6181
    name: catalogi
    type: application
    urls:
    - https://github.com/codegouvfr/catalogi/releases/download/v1.52.3/catalogi-2.0.14.tgz
    version: 2.0.14
generated: "2025-11-07T13:48:10.829793854Z"
